// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIuN_XX709xEiESdejW413gWZQUQ0Ly1o',
    appId: '1:913807132839:web:eeca1a6c972389ba15f382',
    messagingSenderId: '913807132839',
    projectId: 'mis-horarios-61975',
    authDomain: 'mis-horarios-61975.firebaseapp.com',
    databaseURL: 'https://mis-horarios-61975-default-rtdb.firebaseio.com',
    storageBucket: 'mis-horarios-61975.appspot.com',
    measurementId: 'G-T82RT2NE0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQMyhbuTGX3kLGJu024cioO4RJ75UCAfI',
    appId: '1:913807132839:android:d141d8fdbceee37415f382',
    messagingSenderId: '913807132839',
    projectId: 'mis-horarios-61975',
    databaseURL: 'https://mis-horarios-61975-default-rtdb.firebaseio.com',
    storageBucket: 'mis-horarios-61975.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7vYxmGOodACDxtJtkBkXKl9cyZG0Lufc',
    appId: '1:913807132839:ios:1ed5b84f12710bbb15f382',
    messagingSenderId: '913807132839',
    projectId: 'mis-horarios-61975',
    databaseURL: 'https://mis-horarios-61975-default-rtdb.firebaseio.com',
    storageBucket: 'mis-horarios-61975.appspot.com',
    iosBundleId: 'com.example.appSolvertic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7vYxmGOodACDxtJtkBkXKl9cyZG0Lufc',
    appId: '1:913807132839:ios:9b533054614cfe8f15f382',
    messagingSenderId: '913807132839',
    projectId: 'mis-horarios-61975',
    databaseURL: 'https://mis-horarios-61975-default-rtdb.firebaseio.com',
    storageBucket: 'mis-horarios-61975.appspot.com',
    iosBundleId: 'com.example.appSolvertic.RunnerTests',
  );
}
